NervanaSystems/ngraph-tf

.pre-commit-config.yaml
.pylintrc
README.md

Forces `clang-format`, `autopep8`, and `pylint` checks on commits.
This requires developers to `pip install pre-commit` and `pre-commit install`, because, sadly, hooks cannot be directly baked into the repository.  They could be validated with a `pre-receive` hook on the server-side, but that requires GitHub Enterprise which we don't have, so we have to rely on an honor system.
Note that currently `master` fails all checks.  A commit to fix all style would be a good idea.

using pre-commit for hooks

---

CMakeLists.txt

Note that this does *not* work with python tests.
It's as though python was not compiled with `-fsanitize` :trollface:

sanitize cmake build type

---

src/ngraph_encapsulate_pass.cc

Not sure why this hasn't been showing up more often, but this does seem to fix an issue on one of the validation scripts I am playing around with.

Fix segfault in encapsulation due to invalidated iterator

---

test/ci/docker/docker-scripts/run-ngraph-tf-cmdline.sh

The last ngraph-tf automation that needs migrating to use TensorFlow 1.9 is the run-model scripts, used to run inference models.  This PR is for those changes.
Successful test run of tf_cnn_benchmark inference models (with posting to dashboard) at https://aipg-rancher.intel.com/jenkins/algo-lr/job/ngraph-tf-run-model/134/

Modifications to run models using TF1.9 and the ngraph wheel

---

test/ci/docker/docker-run-ngraph-tf-build.sh
test/ci/docker/docker-run-ngraph-tf-cmdline.sh
test/ci/docker/docker-scripts/run-ngraph-tf-build.sh
test/ci/run-premerge-ci-checks.sh

There was a short resnet50 inference validation test in ngraph-tf continuous integration testing. I had to turn it off when I automated CI because there were problems running it with the new "import ngraph" syntax and the large ImageNet dataset could not easily be stored on /dataset.
This PR restores the resnet50 inference validation test in automated CI. Part of this was achieved by changing the dataset used to a smaller 6 gig version of ImageNet.
This PR has a sibling in the cje-algo repo. The whole change is tricky to put in place, as the cje-algo portion must be merged to master before the ngraph-tf portion, in order to avoid breaking production CI for ngraph-tf.  Both the ngraph-tf-unittest and ngraph-tf-daily-build jobs are affected, and must each be tested.
Successful testing of …

Enable resnet50 inference validation check in ngraph-tf CI

---

src/ngraph_builder.cc

Because `BatchToNGraph` mutates the batch node pointer by reference to point to the post-reshaped batch, we need to move it below the `BatchedOpParamToNGraph(...ng_input->get_shape()...)` call.

Fix bug introduced in recent commit with NHWC order

---

test/ci/docker/docker-run-ngraph-tf-cmdline.sh

Reinstate /dataset in docker container for running commands.  It appears to have been lost when porting the script from ngraph-tensorflow-bridge to ngraph-tf. This is needed for running new inference models which use real datasets (instead of synthetic) that are located in /dataset .
Also, mount aipg_trained_dataset at both /aipg_trained_dataset and /trained_dataset in the container.  This provides backwards compatibility for existing run-model jobs, while also standardizing on the /trained_dataset name.  Note that I checked with Nick that doing this host mounted-in-two-places is OK, and we both think it will work.

Reinstate /dataset in docker container for running commands

---

test/ci/docker/Dockerfile.ngraph-tf-ci
test/ci/docker/docker-run-tf-with-ngraph-build.sh
test/ci/docker/docker-scripts/run-tf-with-ngraph-build.sh

Add scripts to automate building of the TensorFlow + nGraph in the same wheel.  While the automation does the builds in a clone of the NervanaSystems/tensorflow repo (which is a fork of tensorflow/tensorflow, used for upstreaming), the automation scripts are kept in the ngraph-tf repo as they are specific to Intel's environment.
The wheel produced has a name like: tensorflow-ngraph-1.10.0rc1-cp27-cp27mu-linux_x86_64.whl
Also update the bazel version used in the Docker containers to 0.16.0.

ngraph-tf repo-side automation for tensorflow-with-ngraph wheels (for r0.4)

---

test/ci/docker/Dockerfile.ngraph-tf-ci

Daily builds of NervanaSystems/tensorflow started failing with an error that said the keras_applicatons python package was not found. This quick PR adds a "pip install keras_applications" to the Dockerfile for the automated builds, which allows the tensorflow build to pass.
This PR has been tested with both ngraph-tf and NervanaSystems/tensorflow automated builds (run manually from the command-line). Both pass.
Successful testing: https://aipg-rancher.intel.com/jenkins/algo/job/ngraph-tf-daily-build/175/

Add keras_applications package to Dockerfile for automated builds

---

maint/apply-code-format.sh
maint/bash_lib.sh
maint/check-code-format.sh
maint/clang_format_lib.sh
test/ci/docker/Dockerfile.ngraph-tf-ci
test/ci/docker/docker-scripts/run-ngraph-tf-build.sh

Porting this stuff over from the main `ngraph` repo. Had to make a few minor changes to the scripts there as follows:
* Different source dir names
* Have to take in `.cc` and `.h` as well
* Exclude `cpu_codegen` from search paths
I think we should merge to `master` rather than `r0.4` to minimize disruption for now. Note that the format check will actually _fail_ on CI for now. I don't want to actually run the format script until `r0.4` and `master` are back together.

Make clang-format check required for CI

---

src/ngraph_assign_clusters.cc
src/ngraph_deassign_clusters.cc

This gives an easier-to-digest log format for cluster assignments, visible when `NGRAPH_VLOG_LEVEL=2`. For example:
```
2018-08-20 14:06:58.295602: I /localdisk/amprocte/tf-di/ngraph-tf/src/ngraph_deassign_clusters.cc:128] FINAL CLUSTER ASSIGNMENT: CLUSTER 0 (7 NODES)
2018-08-20 14:06:58.295609: I /localdisk/amprocte/tf-di/ngraph-tf/src/ngraph_deassign_clusters.cc:130] ===================================================================
2018-08-20 14:06:58.295614: I /localdisk/amprocte/tf-di/ngraph-tf/src/ngraph_deassign_clusters.cc:135] v0/cg/resnet_v17/conv24/conv2d/kernel/Initializer/random_uniform/min[Const]
2018-08-20 14:06:58.295620: I /localdisk/amprocte/tf-di/ngraph-tf/src/ngraph_deassign_clusters.cc:135] v0/cg/resnet_v113/conv44/conv2d/kernel/Initializer/random_uniform/sub[Const] …
```

Better logging of cluster assignments

---

test/ci/docker/docker-run-ngraph-tf-cmdline.sh

Fix for the default run-type for running commands (inference models) in a docker container.

Fix default run-type for docker container command line runs

---

src/ngraph_builder.cc
src/ngraph_encapsulate_op.cc

See NGRAPH-2631 and (maybe) NGRAPH-2099. Marking WIP because I want to evaluate whether the locks around the `create_tensor` calls are too conservative. (In theory they are not needed.)

Fix for crash when inter_op_parallelism_threads>1

---

src/ngraph_encapsulate_op.cc
src/ngraph_utils.cc

Added small change to support UINT16 data type on NGRAPH.
Tested with the NCF model, both the training and inference runs with NGRAPH.

Mingshan/Support UINT16 and enable the NCF to run with NGRAPH

---

test/ci/docker/docker-run-ngraph-tf-cmdline.sh

The only change I could find on "r0.4" that needed to be ported to master was a default run-type for ngraph-tf model testing.  This is a pretty minor change, but will help when doing debugging directly in the ngraph-tf repo.

CI script changes from r0.4 that need to be on master

---

maint/apply-code-format.sh
test/ci/docker/Dockerfile.ngraph-tf-ci-py2
test/ci/docker/Dockerfile.ngraph-tf-ci-py3

ngraph-tf PR#211 made additions to the Dockerfile used for Python 2 builds in CI.  A small bug in this PR caused the Python 3 builds (in ngraph-tf-daily-build) to break when the Python package "yapf" could not be found.
This PR does two specific actions:
1. Fix the bug, as per @sayantan-nervana 's suggestion
1. Balance the Dockerfiles for both Py2 and Py3, by having both "yapf" and "futures" added to both.  In addition, include a comment in the Dockerfiles explaining how these additions are used.
Successful testing of this patch:
ngraph-tf-daily-build: https://aipg-rancher.intel.com/jenkins/algo/job/ngraph-tf-daily-build/263/

Fix Python3 daily-build, plus balance Dockerfile additions

---

test/ci/docker/Dockerfile.ngraph-tf-ci-py2
test/ci/docker/Dockerfile.ngraph-tf-ci-py3

The YoloV2 inference model requires an additional "librosa" python package to run.  I tried adding this as a "pip install librosa" in the command for the daily inference run, but encountered errors.  Thus, I am adding the package in the standard Dockerfiles for ngraph-tf.

Add more packages to Dockerfile for additions to daily inference model runs

---

test/ci/docker/Dockerfile.ngraph-tf-ci-py3

The python imaging library (PIL) package is needed by the UNet infererence model script.
Successful manual testing:
https://aipg-rancher.intel.com/jenkins/algo/blue/organizations/jenkins/ngraph-tf-unittest/detail/ngraph-tf-unittest/720

Add python imaging library package, needed to run some inference models

---

test/ci/docker/Dockerfile.ngraph-tf-ci-py2
test/ci/docker/Dockerfile.ngraph-tf-ci-py3

As of v1.11.0, TensorFlow now seems to require the keras_preprocessing Python package in order to build.  This fix is being done quickly, as CI is not working.

Add keras_preprocessing package to Dockerfiles, to fix broken TF builds

---

test/ci/docker/Dockerfile.ngraph-tf-ci-py3

Ubuntu package libsdl1.2-dev is needed to run the A3C inference model, which @kimjanik is automating.

Add libsdl1.2-dev to Dockerfile for Python3, to run A3C model

---

src/ngraph_encapsulate_op.cc

NNP backend requests that all its tensors must have been destroyed when the backend itself is destroyed. However, in tf-bridge there is some cache still holding this tensor, which can cause exception in some cases.
Fix it by changing of order of backend and caches in the class member section so that backend is created before cache and destroyed after cache was destroyed, when the argon tensors have been released.

Fix of tensor liveness issue

---

src/ngraph_builder.cc
test/python/test_softmax.py

The softmax op expected the dimension = 2 same as TF. But now the TF kernel
for softmax in TF has changed the constraint to >=1 so making that same
change in ngtf fixes the bug.

Fix transformer-LT bug

---

test/ci/docker/dockerfiles/Dockerfile.ngraph-tf-ci-py2
test/ci/docker/dockerfiles/Dockerfile.ngraph-tf-ci-py3
test/ci/docker/dockerfiles/Dockerfile.ngraph_tf.builds_ubuntu1604_gcc48_py35
test/ci/docker/dockerfiles/Dockerfile.ngraph_tf.builds_ubuntu1604_py27
test/ci/docker/dockerfiles/Dockerfile.ngraph_tf.builds_ubuntu1604_py35
test/ci/docker/dockerfiles/Dockerfile.ngraph_tf.inference_ubuntu1604_py27
test/ci/docker/dockerfiles/Dockerfile.ngraph_tf.inference_ubuntu1604_py35

Lock yapf at version 0.24.0, as clang-format-3.9 seems to not be able to work with newer versions of yapf
Successful testing: https://aipg-rancher.intel.com/jenkins/algo/job/ngraph-tf-daily-build/394/

yapf 0.24.0 for clang-format-3.9 in Docker builds

---

test/ci/macos/run-ngraph-tf-mac-build.sh

Mac builds were still using "tensorflow==1.12.0rc2" for builds.  This PR updates them to use "tensorflow==1.12.0".
Successful testing: 
https://aipg-rancher.intel.com/jenkins/algo/job/ngraph-tf-mac-daily-build/86/

Modify Mac builds to use TensorFlow 1.12.0 for builds

---

src/ngraph_mark_for_clustering.cc
test/test_array_ops.cpp

Rejecting all other modes in confirmation pass. Discovered while looking at the dequantize_op_test.DequantizeOpTest.testBasicQint8 test.
The test dequantize_op_test.DequantizeOpTest.testBasicQint8 cannot be included as it runs with "MIN_COMBINED" mode which is not supported by the backend.

Shrestha/ Dequantize Op is supported only in 'Scaled' mode. 

---

python/CreatePipWhl.cmake
python/ngraph_bridge/__init__.in.py

With this change, the generated wheel doesn't have to include libplaidml itself in order for PlaidML to work; PlaidML can be installed separately, as long as the wheel contains libplaidml_backend (which is ngraph code).

Get libplaidml from the plaidml package

---

python/setup.in.py

So check this out--this makes it easy to optionally install ngraph-tf w/PlaidML as a single step, by adding `[plaidml]` to the install command:
(ngraph-tf-test)
rearhart@rearhart-mac01 ~/src/ngraph-tf/build (master)
$ pip install python/dist/ngraph_tensorflow_bridge-0.10.0-py2.py3-none-macosx_10_7_x86_64.whl
Processing ./python/dist/ngraph_tensorflow_bridge-0.10.0-py2.py3-none-macosx_10_7_x86_64.whl
Installing collected packages: ngraph-tensorflow-bridge
Successfully installed ngraph-tensorflow-bridge-0.10.0
(ngraph-tf-test)
rearhart@rearhart-mac01 ~/src/ngraph-tf/build (master)
$ conda list
\# packages in environment at /Users/rearhart/miniconda3/envs/ngraph-tf-test:
\#
\# Name                    Version                   Build  Channel
ca-certificates           2018.12.5 …

Add ngraph-tf plaidml extra dep

---

test/ci/macos/run-mac-build-test-ngtf.sh

This PR adds an automation script in test/ci/macos for running build_ngtf.py and test_ngtf.py on MacOS
Manual testing on aipg-ra-mac-05 shows that the script runs, but there is a unit-test failure in test_ngtf.py (on this branch, which was branched from master yesterday).  If I manually comment out the test_ngtf.py call, then the script fully returns.  Given the unit-test failure, this testing shows that the script is working.

Implement build_ngtf.py automation for MacOS

---

src/ngraph_utils.cc

/proc/self/stat does not exist on Mac because of which mem_str
was an empty string being fed to stol resulting in the
invalid_argument error

Fix the unit test failure on Mac

---

build_ngtf.py
src/ngraph_builder.cc

* Setting the `friendly_name` of the nGraph AllReduce op to the TensorFlow op name for easy correlation in the debug logs
* Enabled printing the order of TensorFlow Horovod ops at the TensorFlow level to help debug out of order execution

avijit/Add diagnostics for debugging AllReduce ops

---

test/ci/docker/docker-run-check-code-format.sh
test/ci/docker/docker-scripts/run-build-test-ngtf.sh
test/ci/docker/docker-scripts/run-check-code-format.sh

Break code-format check out into a separate script, so that it can be run as a separate task once during CI.  This way, testing with other OSes will not need to rely on having the code-format software (clang-format-3.9) installed.

Separate code format check into separate CI task

---

test/ci/docker/docker-run-check-code-format.sh
test/ci/docker/docker-scripts/run-check-code-format.sh

Since active release branch r0.12 uses the same CI system as master, we need to make sure these scripts are added on the r0.12 branch as well.
Successful testing: https://aipg-rancher.intel.com/jenkins/algo/job/ngraph-tf-unittest/1891/

Add separate check-code-format script to r0.12 release branch

---

CMakeLists.txt
README.md
build_ngtf.py
python/setup.in.py
src/version.cc
test/ci/docker/dockerfiles/Dockerfile.ngraph-tf-ci-py2
test/ci/docker/dockerfiles/Dockerfile.ngraph-tf-ci-py3
test/ci/docker/dockerfiles/Dockerfile.ngraph_tf.build_ngtf_ubuntu1604_gcc48_py35
test/ci/docker/dockerfiles/Dockerfile.ngraph_tf.build_ngtf_ubuntu1604_py35
test/ci/docker/dockerfiles/Dockerfile.ngraph_tf.build_ngtf_ubuntu1804_py36
test_ngtf.py

* Changed the name of the build directory to `build_cmake` as the name `build` conflicts with the bazel `BUILD` file for the MacOS.
* Upgraded to TensorFlow 1.13.1 release
* Removed the build option 3 as it's not maintained. The new home for nGraph bridge will be `tensorflow/ngraph_bridge` after the current release.

Rel 0.12.0-rc1 prep

---

CMakeLists.txt
bazel/BUILD
bazel/WORKSPACE
build_ngtf.py
configure_bazel.sh
src/ngraph_encapsulate_op.cc
src/ngraph_timer.h
test_ngtf.py

* Fixed bazel build (upgraded to new API that uses http_archive)
* Added the option to use pre-installed TensorFlow for building nGraph
* Added option to be able to build PlaidML backend
* Removed the option `use_prebuilt_binaries` from build_ngtf.py
* Added event tracing for output copy in NGraphEncapsulate Op.

Avijit/release 0.12.0 prep.02

---

test/ci/junit-wrap.sh

Addition to junit-wrap.sh to exit with the exit status of the test command run (as long as junit-wrap does not fail).  This is safer in that it will insure that the wrapper will trigger any mechanism in the calling script that fires on non-zero exits.  Note that Jenkins should have properly caught any failing xunit tests via the test results import, but having the junit-wrapper also report the exit status of the test script is a good double-check.

junit-wrap.sh exits with status of test command that it wraps

---

test/ci/macos/run-ngraph-tf-mac-build.sh

This update only changes the python2 builds for MacOS.  It updates the builds to use latest tensorflow (i.e. "pip install tensorflow"), since ngraph-bridge now supports the latest TF version 1.13.1.

Update MacOS python2 builds to use latest tensorflow version (1.13.1)

---

test/ci/docker/docker-scripts/run-as-user.sh
test/ci/docker/docker-scripts/run-build-test-ngtf.sh
test/ci/docker/dockerfiles/Dockerfile.ngraph_tf.build_ngtf_centos76_py34

This PR adds the ability to run build_ngtf.py and test_ngtf.py on Centos 7.6 in a docker container.  Note that the _native_ Python 3 in CentOS 7.6 is python 3.4.
This PR also makes the following modifications to general docker scripts:
- run-as-user.sh has been modified to work on both RedHat-derived Linux distros as well as Debian/Ubuntu-derived distros (which were already supported)
- The code-format check has been removed from run-build-test-ngtf.sh, as it was previously broken out into a separate script
Successful testing: besides passing general CI pre-merge checks (see below), I also ran a full round of ngraph-tf-daily-build (four separate Linux builds), all which passed: https://aipg-rancher.intel.com/jenkins/algo/job/ngraph-tf-daily-build/590/

Add support for CentOS 7.6 builds in docker containers

---

build_ngtf.py
maint/apply-code-format.sh
maint/check-code-format.sh
python/CreatePipWhl.cmake
python/ngraph_bridge/__init__.in.py
python/setup.in.py
src/CMakeLists.txt
src/version.cc
src/version.h
test/ci/buildkite/test_runner.py
test_ngtf.py
tools/build_utils.py
tools/test_utils.py

* Added support for including nGraph include files to the Python Whl so that other backends can be built with the binary distribution of `ngraph_tensorflow_bridge`.
* Modified the Python format checking/applying code
* Added API: `ngraph_tf_cxx11_abi_flag()` that returns the value of the `_GLIBCXX_USE_CXX11_ABI` used building the bridge and nGraph library. This will be useful for building other C++ libraries using the bridge (such as a backend).

Avijit/add "include" directory to whl and few enhancements

---

test/ci/docker/docker-scripts/run-ngraph-tf-build.sh
test/ci/docker/dockerfiles/Dockerfile.ngraph-tf-ci-py2

Modifications to get python2 builds (in docker) working again, given how code-format checks have been modified.  Formal code-format check removed from python2 build script because there is now a separate code-format check build task in CI, plus run-premerge-ci-checks.sh runs the code-format check.
Note: this also needs to get into the `r0.12` branch, as daily-builds (which are running off `r0.12`) are currently failing the python2 build task.

Fix python2 docker builds given changes in code-format checks
