NervanaSystems/ngraph-tf

src/ngraph_builder.cc
src/ngraph_confirm_pass.cc
src/ngraph_stub_ops.cc
test/python/test_conv2dbackpropinput.py

clearly, I'm still confused; currently the test crashes

Conv2DBackpropInput

---

src/ngraph_builder.cc

also, removed some stray-seeming prints

refactored input validation

---

src/ngraph_builder.cc

also why were objects passed by value?

removed unused return value spam

---

src/ngraph_builder.cc

Wow the diff is whack.
I've only moved code into separate functions, and made things constant that should've been constant.

using table dispatch for translate graph

---

examples/resnet/models/official_resnet_model.py

minor fix to enable NCHW for official resnet models

fix official resnet model

---

src/ngraph_assign_clusters.cc
test/ci/run-premerge-ci-checks.sh

Create a shadow path in gc between 2 nodes
if we do NOT want them to be colocated

Fix for static input bug

---

test/test_array_ops.cpp
test/test_math_ops.cpp
test/test_utilities.cpp
test/test_utilities.h

1) Math Op test_abs.py
2) Array Op test_fill.py

Sindhu/Conversion of the below pytests to C++ tests

---

src/ngraph_encapsulate_op.cc

1. Fixed a bug in handling the exception (was not getting propagated upstream): JIRA-NGRAPH-2787
2. Expanded the error catching to other areas where nGraph calls are made.
3. Minor cleanups.

Error handling bug fix and add more of it

---

CMakeLists.txt
src/ngraph_deassign_clusters.cc

Log
1. Total Number of Nodes
2. Number of nodes marked for clustering
3. Number of nodes assigned a cluster
4. Number of nGraph Clusters
5. Size of each nGraph Cluster

Shrestha/Add clustering information to NGRAPH_TF_LOG_PLACEMENT.

---

diagnostics/model_test/verify_model.py

- Beautify the test result
- Return exit code

- Show calculated norm value for both passed and failed case

---

CMakeLists.txt
src/ngraph_builder.cc

6e06cded1d30030136d5677e0b3851dd4cc04bee

Updated to latest nGraph

---

src/ngraph_deassign_clusters.cc
src/tf_deadness_analysis.cc

Try to fix the critical error found in klocwork on 11/20/2018.

Fix new klocwork error reports on 11/20/2018

---

src/ngraph_builder.cc

This PR fixes the Klockworks errors. Here's the link to the appropriate view: https://klocwork-ir2.devtools.intel.com:8080/review/insight-review.html#issuelist_goto:project=ngraph_tf,searchquery=state%253A%252BNew,sortcolumn=id,sortdirection=ASC,view_id=8

Fixed klockworks errors

---

src/ngraph_builder.cc

Fix segfault during SplitV Op translation seen while running "split_op_test.SplitOpTest.testNonexistentDimTensor"

Sindhu/Fix SplitV segfault 

---

CMakeLists.txt
build_ngtf.py
src/ngraph_encapsulate_op.cc
test/graph_exec.cpp
test/opexecuter.cpp
test/opexecuter.h

Tested with ng-tf (with tf-master)
Pending test with tf-ng (with tf-master)

Shrestha/fix tf master compilation error and upgrade nGraph version

---

CMakeLists.txt
build_ngtf.py
src/ngraph_encapsulate_op.cc

Added code to removed unneeded tensors after the execution of a cluster is done.

Fix memory leak

---

README.md
python/ngraph_bridge/__init__.in.py
src/ngraph_encapsulate_op.cc
src/ngraph_timer.h
src/version.cc

* Added a Timer class to enable logging of time taken by various stages in NGEncapsulate::Compute(). 
* Added this ID: `NGRAPH_TF_TIMING_PROFILE` for filtering the timing profile
* Enabled printing detailed version information

More diagnostic support

---

bazel/BUILD
bazel/ngraph.BUILD
configure_bazel.sh

* Added the missing symbol. 
* Fixed the version of the TensorFlow to be 1.12.0 
* Added Quantized concat op support.

Fix bazel build

---

CMakeLists.txt
build_ngtf.py
python/setup.in.py
src/version.cc
test/opexecuter.cpp

Fixed a Tensor cleanup and updated the version numbers in preperatio for the next release

Rel-12-prep

---

test/python/tensorflow/tf_unittest_runner.py

1) Raises/prints exception of Error and Fail cases
2) This does not interrupt the tests execution, exception is raised after all the tests run

Sindhu/TF python unit-test runner - catch exception when test fails

---

src/enable_variable_ops/ngraph_capture_variables.cc
src/enable_variable_ops/ngraph_rewrite_pass.cc

Changes to fix building with the --enable_variables_and_optimizers version

Minor Fix for building with --Variable version
